# Generated by Django 5.2.5 on 2026-07-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="qrinteraction",
            new_name="interaction_token_i_fb2324_idx",
            old_name="interactions_token_i_42aa5f_idx",
        ),
        migrations.AlterField(
            model_name="qrinteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("LANDING_VIEW", "LANDING_VIEW"),
                    ("CALL_115_CLICK", "CALL_115_CLICK"),
                    ("DIRECTIONS_CLICK", "DIRECTIONS_CLICK"),
                    ("ALL_CENTERS_CLICK", "ALL_CENTERS_CLICK"),
                    ("SURVEY_START", "SURVEY_START"),
                    ("SURVEY_COMPLETE", "SURVEY_COMPLETE"),
                    ("SURVEY_DECLINED", "SURVEY_DECLINED"),
                ],
                max_length=24,
            ),
        ),
    ]
