# Generated by Django 5.2.5 on 2026-07-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "interactions",
            "0002_rename_interactions_token_i_42aa5f_idx_interaction_token_i_fb2324_idx_and_more",
        ),
        ("qr", "0002_alter_qreventcontext_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="qrinteraction",
            constraint=models.UniqueConstraint(
                fields=("token", "anonymous_session_id", "interaction_type"),
                name="unique_token_session_interaction",
            ),
        ),
    ]
