# Generated by Django 5.2.16 on 2026-08-01 17:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPackage',
            fields=[
                ('package_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_id', models.SlugField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('age_band', models.CharField(choices=[('YOUNG_ADULT', '18–34'), ('MIDDLE_AGE', '35–54'), ('OLDER_ADULT', '55+'), ('GENERAL', 'Genel')], max_length=20)),
                ('video_asset', models.CharField(max_length=320)),
                ('poster_asset', models.CharField(blank=True, max_length=320)),
                ('caption_asset', models.CharField(blank=True, max_length=320)),
                ('duration_ms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('language', models.CharField(default='tr', max_length=12)),
                ('slogan_in_video', models.BooleanField(default=True)),
                ('psychologist_review_status', models.CharField(choices=[('PENDING', 'İnceleme bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Uygun bulunmadı')], default='PENDING', max_length=12)),
                ('health_review_status', models.CharField(choices=[('PENDING', 'İnceleme bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Uygun bulunmadı')], default='PENDING', max_length=12)),
                ('active', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('file_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'content_id'],
                'constraints': [models.UniqueConstraint(fields=('content_id', 'version'), name='unique_content_package_version')],
            },
        ),
    ]
