# Generated by Django 5.2.5 on 2026-07-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("DISABLED", "Disabled")],
                default="ACTIVE",
                max_length=12,
            ),
        ),
    ]
