# Generated by Django 5.2.5 on 2026-07-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qreventcontext",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ENDED", "Ended"),
                    ("EXPIRED", "Expired"),
                ],
                default="ACTIVE",
                max_length=12,
            ),
        ),
    ]
