# Generated by Django 5.2.5 on 2026-07-27 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_status"),
        ("qr", "0002_alter_qreventcontext_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSupportToken",
            fields=[
                (
                    "token_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("status", models.CharField(default="ACTIVE", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="qrdisplaysession",
            name="idempotency_key",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddConstraint(
            model_name="qrdisplaysession",
            constraint=models.UniqueConstraint(
                fields=("device", "idempotency_key"), name="unique_display_idempotency"
            ),
        ),
        migrations.AddField(
            model_name="devicesupporttoken",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="support_tokens",
                to="devices.device",
            ),
        ),
    ]
