# Generated by Django 5.2.16 on 2026-08-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yedamcenter',
            options={'ordering': ['city', 'district', 'center_name']},
        ),
        migrations.AddField(
            model_name='yedamcenter',
            name='coordinate_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='yedamcenter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='yedamcenter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
