# Generated by Django 5.2.5 on 2026-07-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="metric_key",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="reverse_scored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="consent_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="consent_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="context_mode",
            field=models.CharField(default="GLOBAL_GENERAL", max_length=20),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="context_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="privacy_notice_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="survey_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
