# Generated by Django 5.2.16 on 2026-08-01 17:15

from django.db import migrations, models


def populate_legacy_codes(apps, schema_editor):
    question_model = apps.get_model("surveys", "SurveyQuestion")
    for question in question_model.objects.filter(code=""):
        question.code = f"LEGACY_{question.position}_{str(question.question_id)[:8]}"
        question.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyquestion_metric_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='allow_not_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='code',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='display_condition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='section',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(populate_legacy_codes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="surveyquestion",
            constraint=models.UniqueConstraint(
                fields=("survey", "code"), name="unique_survey_question_code"
            ),
        ),
    ]
